### ISSUE TITLE
开启自动排序后物品变为紫黑方块，但不影响烧制

### ISSUE THREAD

**Issue by RuiXuqi** [sddsd2332/MEK-1.12.2-v10#10]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/90179819/214002626-62b0d026-b69e-4d3e-b6bb-2c225f7f9066.png">
测试物品为铁矿

**Comment by sddsd2332** [comment]
同步社区版分支后出现问题
在那边丢issues了
https://github.com/Thorfusion/Mekanism-Community-Edition/issues/87
应该是这个仓库在修改插槽平衡的时候出问题了
https://github.com/thedeadferryman/Mekanism/commit/34c258d498e87ac75a15da1ee5035259f9ccab06

**Comment by sddsd2332** [comment]
现在配方起码不会黑白了，但是部分配方会出现问题
比如木头烧成木炭，但是熔炼 会变成 木头烧煤炭 这样:(

**Comment by sddsd2332** [comment]
发现一个[输入插槽可以覆盖物品并复制物品问题](https://github.com/Thorfusion/Mekanism-Community-Edition/issues/87#issuecomment-1424305962)，需要重写排序
准备回滚到原来的版本,等有空试试看不能不修

**Comment by magcicada** [comment]
这个问题太搞笑了，试了试指定物品状态还是会像你发的视频一样复制物品，不好搞就回滚不管了吧，反正看着只有重写排序这条路。

**Comment by sddsd2332** [comment]
现在对工厂的排序添加了控制文件【默认是旧排序】
现在基本上不会出现强制覆盖了不同物品
[但是会有相同ID方块的不同meta状态下，输出物品是相同，且获取方式是矿物词典时，会从左到右覆盖相同ID的物品](https://github.com/Thorfusion/Mekanism-Community-Edition/issues/87#issuecomment-1435909810)

**Comment by sddsd2332** [comment]
先关闭了，
如果有好的其他新排序丢PR给我或Mekanism-Community-Edition那边
我在拉取
