### ISSUE TITLE
能量和热量tab加上显示

### ISSUE THREAD

**Issue by RuiXuqi** [sddsd2332/MEK-1.12.2-v10#12]
<img width="72" alt="image" src="https://user-images.githubusercontent.com/90179819/214198653-a99b6eb4-8da2-44a4-bbcf-acde352ef1ca.png">
就这两，想做成新版样式的，但是新版会显示当前的单位，旧版不显示，又要动mod本体（

**Comment by sddsd2332** [comment]
ok
已更新到新版本的样子

https://user-images.githubusercontent.com/21332467/215242585-2654f034-70ad-45fe-9473-94317828a5ff.mp4
