### ISSUE TITLE
文件编码在IDEA中报错

### ISSUE THREAD

**Issue by magcicada** [sddsd2332/MEK-1.12.2-v10#20]
你们编码都不用IDEA的吗，为啥全都是用GBK在码东西，我一导进IDEA中直接全红报UTF-8编码识别不了，一看全是中文符号，好家伙。
![image](https://user-images.githubusercontent.com/45464670/217745274-ad3b5603-5af0-4650-9e22-8427f9e36865.png)
编译倒是没问题，但是IDEA中功能全用不了了

**Comment by sddsd2332** [comment]
我不清楚，但是我本地使用IDEA没这问题...

**Comment by magcicada** [comment]
因为你IDEA就是用的GBK吧...

**Comment by magcicada** [comment]
不信你就看en_us.lang,里面有几个括号进游戏就是乱码。

**Comment by sddsd2332** [comment]
不，全局是UTF-8，但是有三个文件设置了GBK
![设置IDEA](https://user-images.githubusercontent.com/21332467/217749448-35b6a62e-ab5c-47c7-a132-ece8680fca15.png)

**Comment by magcicada** [comment]
好家伙，报错的就有我刚才说的其中两个

**Comment by sddsd2332** [comment]
等下修下
