### ISSUE TITLE
modrinth.com搬运申请

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [sddsd2332/MEK-1.12.2-v10#22]
希望作者能将mod上传到modrinth，或者进行对所有人的搬运授权，感谢了！

**Comment by mczph** [comment]
符合协议的话可以直接包含在Modrinth整合包内（如果没过的话可以提供一下作者同意的截图，毕竟这个fork他们的管理应该不知道）（当然上传更好）

**Comment by sddsd2332** [comment]
传，都可以传，
传之前记得先问问原mek作者同不同意分发我这个修改版本

**Comment by mczph** [comment]
https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/184
Please also update to Curseforge

**Comment by sddsd2332** [comment]
我等下问问能不能原mek作者能不能传，如果可以就传modrinth和Curseforge上

**Comment by sddsd2332** [comment]
Curseforge:https://www.curseforge.com/minecraft/mc-mods/mekanism-unofficial-edition-v10-edition
