### ISSUE TITLE
流体未注册

### ISSUE THREAD

**Issue by Han0630** [sddsd2332/MEK-1.12.2-v10#23]
过热的纳蒸汽
![) U6HHAW(1`U0N@JM~{GRZ4](https://user-images.githubusercontent.com/88375967/226864278-035ea798-31be-42b8-a825-c1133133c66e.jpg)
![OWPJZ1L_ ZKD}6AI3YBLHZ8](https://user-images.githubusercontent.com/88375967/226864290-629b541a-9195-44dc-aeb3-154e914e55a6.png)
![CG0KZ71MU` A1@AVM~2K84X](https://user-images.githubusercontent.com/88375967/226864305-04c5cb04-0e5d-48e0-bbae-0af00e19c620.png)

貌似不能使用此流体参与crt魔改

**Comment by sddsd2332** [comment]
发你的zs脚本
这个流体是 liquidsuperheatedsodium

**Comment by Han0630** [comment]
ct hand 获取到的参数是这个。
![W}}GYKHCMQ511UMI4E)Q9}T](https://user-images.githubusercontent.com/88375967/226868815-fa98d723-06ee-45dd-9071-46f9141dbac6.png)

**Comment by mczph** [comment]
哥们这是Extra Cells模组生成的啊，你要是要气体用crt导出列表，你这ct hand出来的本质上还是流体

**Comment by Han0630** [comment]
这是液体啊哥们

**Comment by Han0630** [comment]
> 哥们这是Extra Cells模组生成的啊，你要是要气体用crt导出列表，你这ct hand出来的本质上还是流体
![33OZ4UH~{8ZNYQZJ1QLBN1T](https://user-images.githubusercontent.com/88375967/226874243-0578d6e0-ecc4-44a8-b2bb-6c7726271090.png)
![ACMQ6 OV%F9QS_CZM W{7WU](https://user-images.githubusercontent.com/88375967/226874252-613eec82-6ccb-4891-a9d8-87e07a25c539.png)
