### ISSUE TITLE
通用线缆问题

### ISSUE THREAD

**Issue by hellominecraftlauncher** [sddsd2332/MEK-1.12.2-v10#26]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
放置一个通用线缆到能量塔（DCmod），不能是终极线缆，以下的线缆用合金升级的时候概率性电会停止，且挖掉重放没用，也就是目前有一个线缆（例如精英线缆）了，然后用合金升级的时候TOP/waila显示从抽电5000RF（已更改）变成了0RF，挖掉重放后依然如此

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2860
**Mekanism:9.8.11.150 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by sddsd2332** [comment]
无法复现
缺少详细信息，需要更多信息才能确认
像这类问题请先提供详细日志或视频，或者一起提供
暂时关闭
