### ISSUE TITLE
有机农场与反质子核合成器CrT无法添加配方?

### ISSUE THREAD

**Issue by ChingTing2586** [sddsd2332/MEK-1.12.2-v10#29]
在使用CrT为V10新增的几个机器添加配方时出现如下问题与反馈
模组均为最新版

1.有机农场CrT无法添加配方
使用/ct mekrecipes organicfarm可正常导出已有的配方
添加配方示例：
`mods.mekanism.organicfarm.addRecipe(<botania:vineball>, <gas:nutrientsolution>, <minecraft:vine> * 12, <botania:vineball>, 1.0);` 
报错：No such member:organicfarm

2.反质子核合成器CrT无法添加配方
使用/ct mekrecipes antiprotonicnucleosynthesizer无法导出配方
报错：在执行此命令时出现了未知的错误
翻看源码时看到下图中的信息，红框处或为问题所在
MekRecipesCommand.java（第287与302行）
反质子核合成器与加压反应室（PRC）重复，因此执行/ct mekrecipes prc时会产生同上相同的错误
[图示](https://sm.ms/image/3zFwIiWuypvP4VL)

3.营养液化器、环境气体收集器是否支持CrT
这两个机器添加配方目前只支持GrS但还未支持CrT

4.环境气体收集器所产出的“不稳定纬度气体”是否有加速方法或纬度需求？

其他新增机器可正常添加配方
感谢！

**Comment by sddsd2332** [comment]
首先 感谢你测试了MEKV10对CrT机器兼容测试【我只是写了代码但没使用CrT进行配方测试】
> 1.有机农场CrT无法添加配方 使用/ct mekrecipes organicfarm可正常导出已有的配方 添加配方示例： `mods.mekanism.organicfarm.addRecipe(<botania:vineball>, <gas:nutrientsolution>, <minecraft:vine> * 12, <botania:vineball>, 1.0);` 报错：No such member:organicfarm

这个是我内部代码写错导致的，下个版本修复
> 2.反质子核合成器CrT无法添加配方 使用/ct mekrecipes antiprotonicnucleosynthesizer无法导出配方 报错：在执行此命令时出现了未知的错误 翻看源码时看到下图中的信息，红框处或为问题所在 MekRecipesCommand.java（第287与302行） 反质子核合成器与加压反应室（PRC）重复，因此执行/ct mekrecipes prc时会产生同上相同的错误 [图示](https://sm.ms/image/3zFwIiWuypvP4VL)

这个是老早以前使用PRC的代码实现的，同样下个版本修复
> 3.营养液化器、环境气体收集器是否支持CrT 这两个机器添加配方目前只支持GrS但还未支持CrT

营养液化器下个版本增加CrT的配方需求
环境气体收集器我要看下怎么实现，这可能需要其他人帮助
> 4.环境气体收集器所产出的“不稳定纬度气体”是否有加速方法或纬度需求？

环境气体收集器没有加速方法，但是有维度的需要
后面会加个用电的版本，那个就可以升级了

**Comment by xy177** [comment]
这个问题已经被解决了么，但是目前我使用了150版本但是尝试添加和移除配方仍旧会报no such member:organicfarm
