### ISSUE TITLE
Mekanism P2P incompatiblities

### ISSUE THREAD

**Issue by Gandalf360one** [sddsd2332/MEK-1.12.2-v10#31]
#### Issue description:
First of all: I dont know if the Bug is caused by Applied Energistics 2 extendet life or Mekanism Unofficial Edition: V10 Edition!
I try to use P2p FE Tunnels to support Mekanism Machines with Energy but when I have more than one Machines bind to the same Input (p2p) non of the 2 machines will receive energy.
**This bug doesnt exist in the original Mekanism version.**

#### Steps to reproduce:
https://youtu.be/3sZDPLpx-_I

#### Issue description:
First of all: I dont know if the Bug is caused by Applied Energistics 2 extendet life or Mekanism Unofficial Edition: V10 Edition!
When a Machine is placed next to a P2p FE Tunnel which is already linked it wont receive any energy. It will only receive energy when the p2p Tunnel is attached and linked after the Machine is placed.
**This bug doesnt exist in the original Mekanism version.**

#### Steps to reproduce:
https://youtu.be/hzzWYTT_ly0

#### Version (make sure you are on the latest version before reporting):
**Forge:**  1.12.2-14.23.5.2860
**Mekanism:** 1.12.2-9.8.11.150-sddsd2332
**Other relevant version:** 
**AppliedEnergistics2:** appliedenergistics2-rv6-stable-7-extended_life-v0.55.13

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/vJnC2FNR

**Comment by sddsd2332** [comment]
I'll take a look

**Comment by sddsd2332** [comment]
Ask a question,
Will the same issue occur with mekce-1.12.2?

**Comment by Gandalf360one** [comment]
Ehm I m really sorry for wasteing your time.
I tested more around and found out that Applied Energistics 2 extendet life cause the issue.
Didnt found the issue ealier because every worked as exspected in my modpack testing world
Sorry again.

**Comment by sddsd2332** [comment]
Never mind
I tested the original AE locally and didn't get this no issue either
It may be caused by AE2UEL moving the original code
If needed
My side can try to adapt

**Comment by Gandalf360one** [comment]
Created a ticket at the AE2EL issue tracker
https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/271
