### ISSUE TITLE
CrT command error

### ISSUE THREAD

**Issue by Shepherd23333** [sddsd2332/MEK-1.12.2-v10#33]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
/ct mekrecipes prc执行错误，crafttweaker.log没有输出

#### Steps to reproduce:
/ct mekrecipes prc

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2860
**Mekanism:** 9.8.11.150
**CraftTweaker:** 1.12.2-4.1.20.688

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
latest.log:https://mclo.gs/KhVJtlD

**Comment by sddsd2332** [comment]
该问题已经修复，暂时未发布到cf上，请下载构建版本
参考#29 中问题
